name: jellyfin
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - "8096:8096" #Port par défaut
      - "7359:7359" #Autodiscovery
      - "1900:1900" #DLNA
    network_mode: 'bridge'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /media/medias
        target: /media
    restart: 'unless-stopped'
# On déploie le transcodage nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

