name: LLM # Ollama + OpenWebUI
services:
  ollama:    
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
          reservations:
              devices:
                  - driver: nvidia
                    count: all
                    capabilities:
                        - gpu

  open-webui:
    container_name: open-webui 
    image: ghcr.io/open-webui/open-webui:cuda
    ports:
        - 8080:8080
    volumes:
         - ./open-webui:/app/backend/data
    environment:
        - 'OLLAMA_BASE_URL=http://ollama:11434'
    restart: always
    deploy:
      resources:
          reservations:
              devices:
                  - driver: nvidia
                    count: all
                    capabilities:
                        - gpu